BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `WiringDiagram` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`OpenTime`	INTEGER NOT NULL,
	`Duration`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `UtilTools` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Type`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `UploadClick` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Tutorial` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`isClick`	INTEGER NOT NULL,
	`Page`	INTEGER NOT NULL,
	`OpenTime`	INTEGER NOT NULL,
	`Duration`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Launching` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`OpenTime`	INTEGER NOT NULL,
	`Duration`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Graph` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`FileID`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Error` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL,
	`Message`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `EditSceneName` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`ObjectID`	TEXT NOT NULL,
	`NewName`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `CopyCode` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `ConfigDevice` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`ObjectID`	TEXT NOT NULL,
	`RealHW`	TEXT NOT NULL,
	`isAuto`	INTEGER NOT NULL,
	`Port`	TEXT,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `ClickorDragBeginButton` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Action`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `ClickURL` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL,
	`URL`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `ChangeDeviceName` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`ObjectID`	TEXT NOT NULL,
	`newName`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Canvas` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`HowtoDrag`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `AddorDelDevice` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`App_ID`	TEXT NOT NULL,
	`Action`	TEXT NOT NULL,
	`Object_ID`	TEXT NOT NULL,
	`Type`	TEXT NOT NULL,
	`Time`	INTEGER NOT NULL
);
COMMIT;
