package io.makerplayground.ui;

public enum ExportResult {
    OK,
    DEVICE_OR_PORT_MISSING, CANT_GENERATE_CODE, CANT_CREATE_PROJECT, CANT_WRITE_CODE, MISSING_LIBRARY_DIR, CANT_FIND_LIBRARY, FAIL_TO_CREATE_ARCHIVE, ERROR
}
