name: Build and Deploy MakerPlayground for Windows

on:
  push:
    branches:
      - github-action

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew createBundle
      - name: Extract version from version.json
        id: get-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'src/main/resources/version.json'
          prop_path: 'version'
      - run: echo ${{ steps.get-version.outputs.prop }}
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pyyaml
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Build the library
#        run: |
#          python build.py
#      - name: Get the version number
#        id: get-version-string
#        run: |
#          echo "VERSION_STRING=$(ls *.zip | sed -e 's/\.zip$//')" >> "$GITHUB_OUTPUT"
      - name: Push tag
        id: push-commit-tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get-version.outputs.prop }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.push-commit-tag.outputs.new_tag }}
          body: ${{ github.event.head_commit.message }}
          fail_on_unmatched_files: true
          files: |
            package/windows/Output/*.zip